### ISSUE TITLE
Thank you + feature request

### ISSUE THREAD

**Issue by oadslug** [jmuspratt/craft-fieldguide#4]
Great plugin. Very helpful. Thank you!

If you ever get a chance, and feel like it, I think that it would be really useful to also show unused fields. During the design process on a complicated site, I often create fields, then decide to do something a different way. When I do my final cleanup, I like to delete these — but it's always scary deleting a field not knowing for sure if it's being used somewhere.

**Comment by jmuspratt** [comment]
That definitely makes sense. I will have to research how to find unused fields. Sounds do-able though.

**Comment by oadslug** [comment]
I forked the plug-in and added a new "Unused Fields" section. Have a look. https://github.com/oadslug/craft-fieldguide

Feel free to merge this back in if you like the changes. (I think that the forked repo is public — if not, let me know.)

**Comment by jmuspratt** [comment]
Perfect, thanks Douglas!
